### PR TITLE
Move all storyboard calculations to `osu-classes`

### PR DESCRIPTION
**Pull request by kionell**
What has changed with this update:
1. Deprecated stuff was removed from storyboards.
2. Command loops are now unrolled at the stage of storyboard parsing. You don't need to unroll them at render time, which makes creating timeline elements a bit easier.
3. Easing & lerp stuff was also moved to `osu-classes`. You can get progress of the command and current sprite values directly from the storyboard elements & commands.

### CODE REVIEW

**Comment by kionell** [comment]
Some benchmarking stuff on [world.execute](https://35b36301.kionell-osu-js.pages.dev/play/?1006822):

Before:
before1
before2
before3

After:
after1
after2
after3

**Comment by kionell** [comment]
@blueberrymuffin3 I also wanted to ask if it's possible to somehow optimize hit object rendering?

**Comment by kionell** [comment]
Spector showed the following results for the same frame:

Without hit objects:
commands_no_hitobjects

With hit objects:
commands

With hit objects and song progress bar:
commands_full

**Comment by kionell** [comment]
I'm not sure if such a large increase in commands is a big problem or not

**Comment by kionell** [comment]
For some reason, performance is much worse on a cloudflare deployment than on a local server.

Cloudflare:
image

Local server:
cloudflare

**Comment by blueberrymuffin3** [comment]
> I'm not sure if such a large increase in commands is a big problem or not

So far, I haven't seen a significant impact on performance, but it could be highly browser, driver, and platform specific. If we wanted to improve performance of hitobjects, there are a few things that I thought of:
- Because of the masking applied to the triangles, circles can't be batched with everything else. The number of draw calls could be reduced by batching together additive and normally blended sprites by rendering additive sprites under normal blending modes, but with a zeroed-out alpha channel (works because pixi uses premultiplied alpha), however this would either require a custom batch renderer and/or a much more complex atlas generator. Circles have a mix of normal and additive sprites.
- Rendering sliders directly onto the main frame buffer instead of a render texture. This would require two render passes (reducing overdraw, but adding another draw call), and would require them to rendered every frame instead of just when they are changed, so I don't know if it'd actually help performance. Overall, sliders could be optimized significantly, but it'd require a lot (more) complexity to be added.

I haven't implemented any of these because hit objects haven't had a significant measurable impact on performance in my tests (please let me know if you have a counterexample!).

**Comment by blueberrymuffin3** [comment]
> For some reason, performance is much worse on a cloudflare deployment than on a local server.
> 
> Cloudflare:
> image
> 
> Local server:
> cloudflare

That's weird, I have a hunch that it has something to do with the minifier (esbuild) affecting the JIT compiler, but I'm not sure. I'll run some tests to look into it further.

Edit: Turning off the minifier didn't help, so the performance drop is probably being caused by rollup somehow?

**Comment by blueberrymuffin3** [comment]
@kionell This PR seems to cause a couple graphical bugs in world.execute(me);

https://osu-js.pages.dev/play/?1006822:
image

https://storyboard-optimization.kionell-osu-js.pages.dev/play/?1006822:
image

Notice the spinning thing on the left seems to be stopping early, this could be related to loop unrolling, but I'm not sure

**Comment by kionell** [comment]
> related to loop unrolling

Oops, I know why this is happening. It's related to [this](https://github.com/kionell/osu-classes/commit/a2bf29d53c822385812de2451b1dd01ad5d45f51) commit. When I made this change, I was looking at [this](https://github.com/Wieku/danser-go/blob/master/app/storyboard/loop.go#L58) line from the danser's code and it caused a little confusion

**Review by blueberrymuffin3 — APPROVED** [review]

**Pull request merged**
